### ISSUE TITLE
Evebox crashing under master

### ISSUE THREAD

**Issue by Glasgesicht** [ccdcoe/frankenstack#2]
https://github.com/ccdcoe/frankenstack/blob/master/ansible/roles/deploy_evebox/defaults/main.yml#L2
Using jasonish/evebox:master as it is will cause the docker container constantly crash.

For now, this can be worked around by using latest (as long they're not being merged)

**Comment by markuskont** [comment]
Implemented workaround to use stable image. Needs to be updated once the master becomes new stable.
